apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: $deploy_name
  namespace: $namespace
spec:
  progressDeadlineSeconds: 600
  replicas: $replicas_size
  selector:
    matchLabels:
      app: $lable_value
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: $lable_value
    spec:
      containers:
      - image: $image
        imagePullPolicy: IfNotPresent
        name: $name
        ports:
        - containerPort: $port
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 500Mi
      serviceAccount: $service_account
      serviceAccountName: $service_account
