apiVersion: v1
kind: Service
metadata:
  namespace: $namespace
  name: $name
  labels:
    app: $name
spec:
  type: $type
  ports:
    - port: $port
      targetPort: $targetport
      name: $name
  selector:
    app: $name
